apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_NAME: {{ .Values.secrets.dbName | quote }}
  DB_USER: {{ .Values.secrets.dbUser | quote }}
  DB_PASS: {{ .Values.secrets.dbPass | quote }}
  DB_HOST: {{ .Values.secrets.dbHost | quote }}
  DB_PORT: {{ .Values.secrets.dbPort | quote }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  AWS_STORAGE_BUCKET_NAME: {{ .Values.secrets.awsStorageBucketName | quote }}
  AWS_S3_REGION_NAME: {{ .Values.secrets.awsS3RegionName | quote }}
  EMAIL_HOST_USER: {{ .Values.secrets.emailHostUser | quote }}
  EMAIL_HOST_PASSWORD: {{ .Values.secrets.emailHostPassword | quote }}